version: 2.1

jobs:
  run-tests:
    docker:
      - image: cimg/node:14.16.0
    
    steps:
      - checkout
      - run: "npm install"
      - run: "npm test"

workflows:
  tests-workflow:
    jobs:
      - run-tests
